##only support 3 level config info
#config fo agent
motan-agent:
  port: 9981 # agent serve port. 
  mport: 8002 # agent manage port
  log_dir: "./mesh-logs" 
  registry: "direct-registry" # registry id for registering agent info 
  application: "weibo-mesh" # agent identify. for agent command notify and so on  

#config of registries
motan-registry:
  direct-registry: # registry id 
    protocol: direct   # registry type. will get instance from extFactory.
    host: 127.0.0.1 # direct server ip in single ip. if has host, address will disable.
    port: 8100 #direct server port
    # address: "10.210.21.1:8002,10.210.21.2:8002" # direct server in multi ip

  registry-direct-motan-openresty: # registry id 
    protocol: direct   # registry type. will get instance from extFactory.
    host: 10.211.55.3 # direct server ip in single ip. if has host, address will disable.  
    port: 2234 # use server direct
  # zk-registry:
  #   protocol: zookeeper
  #   host: 10.210.235.157
  #   port: 2181
  #   registrySessionTimeout: 10000
  #   requestTimeout: 5000 

#conf of basic services
motan-basicService:
  mesh-server-basicService: # basic refer id
    group: motan-server-mesh-example # group name
    protocol: motan2 # rpc protocol
    registry: "direct-registry" # registry id
    filter: "accessLog" # filter registed in extFactory
    serialization: simple
    nodeType: server

#conf of services
motan-service:
  cgi-mesh-example-helloworld:
    path: com.weibo.motan.HelloWorldService
    export: "motan2:9991"
    provider: cgi
    CGI_HOST: 10.211.55.3
    CGI_PORT: 9000
    CGI_REQUEST_METHOD: GET
    CGI_SCRIPT_FILENAME: /media/psf/g/idevz/code/z/git/motan-examples/php-server/index.php
    CGI_DOCUMENT_ROOT: /media/psf/g/idevz/code/z/git/motan-examples/php-server
    basicRefer: mesh-server-basicService
  http-mesh-example-helloworld:
    path: com.weibo.motan.HelloWorldService
    export: "motan2:9990"
    provider: http
    HTTP_REQUEST_METHOD: GET
    HTTP_URL: http://10.211.55.3:9900/http_server
    basicRefer: mesh-server-basicService
  cgi-mesh-example-benchmark:
    path: com.weibo.motan.benchmark.BenchmarkService
    export: "motan2:9991"
    provider: cgi
    CGI_HOST: 10.211.55.3
    CGI_PORT: 9000
    CGI_REQUEST_METHOD: GET
    CGI_SCRIPT_FILENAME: /media/psf/g/idevz/code/z/git/motan-examples/php-server/index.php
    CGI_DOCUMENT_ROOT: /media/psf/g/idevz/code/z/git/motan-examples/php-server
    basicRefer: mesh-server-basicService
  http-mesh-example-benchmark:
    path: com.weibo.motan.benchmark.BenchmarkService
    export: "motan2:9990"
    provider: http
    HTTP_REQUEST_METHOD: GET
    HTTP_URL: http://10.211.55.3:9900/http_server
    basicRefer: mesh-server-basicService

#conf of basic refers
motan-basicRefer:
  mesh-client-basicRefer: # basic refer id
    group: motan-openresty-example
    protocol: motan2 # rpc protocol
    registry: registry-direct-motan-openresty
    requestTimeout: 1000
    haStrategy: failover
    loadbalance: roundrobin
    serialization: simple
    filter: "accessLog" # filter registed in extFactory
    retries: 0

#conf of refers
motan-refer:
  mesh-helloworld-call-motan-openresty:
    path: com.weibo.motan.HelloWorldService # e.g. service name for subscribe
    basicRefer: mesh-client-basicRefer # basic refer id
  mesh-benchmark-call-motan-openresty:
    path: com.weibo.motan.benchmark.BenchmarkService # e.g. service name for subscribe
    basicRefer: mesh-client-basicRefer # basic refer id
